[project]
authors = ["Seth Stadick <seth_stadick@bio-rad.com>"]
channels = [
    "conda-forge",
    "https://conda.modular.com/max",
    "https://repo.prefix.dev/modular-community",
    #"https://conda.modular.com/max-nightly/"
]
description = "Code for a demo presentation of Mojo."
name = "mojo-demo"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
#max ="*"
max = "=25.3.0"
# extramojo = ">=0.13.0,<0.14"
# python = ">=3.12.9,<3.13"
# cowpy = ">=1.1.5,<2"
