[project]
authors = ["Seth Stadick <seth_stadick@bio-rad.com>"]
channels = [
    "conda-forge",
    "https://conda.modular.com/max",
    "https://repo.prefix.dev/modular-community",
]
description = "Code for a demo presenation of Mojo."
name = "mojo-demo"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
max = "=25.1.0"
extramojo = ">=0.9.0,<0.10"
python = ">=3.12.9,<3.13"
cowpy = ">=1.1.5,<2"
